/**
 * Casper CSP Migration Tool - Backend Engine
 * VERSION: 2.0.3
 */

const APP_VERSION = "2.0.3";
const DEPLOYMENT_ENVIRONMENT = "DEV";

const ENVIRONMENT_SETTINGS = {
  DEV: {
    mapperUrl: "https://docs.google.com/spreadsheets/d/1wVd0ETR-kRlnFcBrwLBw229qJ1gYZ3y3leGbnj3cn24/edit?gid=0#gid=0",
    destinationUrl: "https://docs.google.com/spreadsheets/d/1wycfLNwduWrGLjfzjng701beyVk3YIzVCdl38rMc_v0/edit?gid=363370443#gid=363370443"
  },
  STAGING: {
    mapperUrl: "https://docs.google.com/spreadsheets/d/1FDfIAZtmO-bwhwQkmBTXfRPFfXSq3ilKSeY9kDzlGvA/edit?gid=0#gid=0",
    destinationUrl: "https://docs.google.com/spreadsheets/d/11iZYwVdwlyC4x7kOwE4RXtfg_6Pp7dpvObrRGicfn7g/edit?gid=363370443#gid=363370443"
  },
  PROD: {
    mapperUrl: "PASTE_PROD_MAPPER_URL_HERE",
    destinationUrl: "PASTE_PROD_DESTINATION_URL_HERE"
  }
};

function getSystemSettings() {
  const settings = ENVIRONMENT_SETTINGS[DEPLOYMENT_ENVIRONMENT];
  if (!settings) {
    throw new Error("v" + APP_VERSION + " Error: Unknown deployment environment '" + DEPLOYMENT_ENVIRONMENT + "'.");
  }

  const missingSettings = Object.keys(settings).filter(key => !settings[key] || settings[key].startsWith("PASTE_"));
  if (missingSettings.length > 0) {
    throw new Error("v" + APP_VERSION + " Error: " + DEPLOYMENT_ENVIRONMENT + " settings are not configured: " + missingSettings.join(", ") + ".");
  }

  return settings;
}

// =================================================================
// SECTION 1: WEB APP ENTRY POINT
// =================================================================
function doGet() {
  const page = HtmlService.createTemplateFromFile('Index');
  page.deploymentEnvironment = DEPLOYMENT_ENVIRONMENT;
  return page.evaluate()
    .setTitle('Casper CSP Migration Tool v' + APP_VERSION + ' (' + DEPLOYMENT_ENVIRONMENT + ')')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// =================================================================
// SECTION 2: DATA MATRIX GENERATION (STAGE 1)
// =================================================================
function loadDataMatrix(payload) {
  const { originUrl, accountId } = payload;

  if (!originUrl || !accountId) {
    throw new Error("v" + APP_VERSION + " Error: Origin URL and Account ID are required.");
  }

  const systemSettings = getSystemSettings();

  console.log("loadDataMatrix start: opening origin and mapper sheets.");
  const originSpreadsheet = SpreadsheetApp.openByUrl(originUrl);
  const mapperSpreadsheet = SpreadsheetApp.openByUrl(systemSettings.mapperUrl);
  const mapperSheet = mapperSpreadsheet.getSheetByName("Mapper") || mapperSpreadsheet.getActiveSheet();

  if (!mapperSheet) {
    throw new Error("v" + APP_VERSION + " Error: 'Mapper' sheet tab was not found.");
  }

  const originSheets = originSpreadsheet.getSheets();
  console.log("loadDataMatrix: origin workbook has " + originSheets.length + " sheets.");
  const originSheetsCache = {};
  originSheets.forEach(sheet => {
    const sheetName = sheet.getName().trim();
    const rawSheetRows = sheet.getDataRange().getValues();
    const filteredRows = prepareOriginSheetRows(rawSheetRows, sheetName);

    originSheetsCache[sheetName.toLowerCase()] = filteredRows;
    const skippedRows = sheetName.toLowerCase() === "objectives" ? 2 : 0;
    console.log("loadDataMatrix: cached sheet '" + sheetName + "' with " + filteredRows.length + " rows after skipping " + skippedRows + " preamble row(s) and removing blank column B entries.");
  });

  const mapperData = mapperSheet.getDataRange().getValues();
  console.log("loadDataMatrix: mapper rows loaded = " + mapperData.length);
  mapperData.shift(); // Remove header row

  // Target 3 tabs strictly
  const destGroupedMappings = {
    "Objectives": [],
    "Key Results": [],
    "Work Streams": []
  };

  // Group rules by Column A value
  mapperData.forEach(row => {
    const colA = String(row[0] || '').trim().toLowerCase();
    if (!colA) return;

    const colGValue = String(row[6] || '').trim().toLowerCase();

    const rule = {
      destCategory: String(row[0] || '').trim(),
      destColIndex: parseColumnIndex(row[1]),          // Column B
      destColRaw: String(row[1] || '').trim(),        // Column B raw
      destFieldName: String(row[2] || '').trim(),     // Column C
      originSheetName: String(row[3] || '').trim(),   // Column D
      originColIndex: parseColumnIndex(row[4]),        // Column E
      originFieldName: String(row[5] || '').trim(),   // Column F
      isAutogenerated: colGValue === 'yes',             // Column G
      isDateGenerated: colGValue === 'date',           // Column G
      isUiObtained: String(row[7] || '').trim().toLowerCase() === 'yes'      // Column H
    };

    if (colA === "objectives" || colA === "objective") {
      destGroupedMappings["Objectives"].push(rule);
    } else if (colA === "key results" || colA === "key result" || colA === "kr") {
      destGroupedMappings["Key Results"].push(rule);
    } else if (colA === "work streams" || colA === "workstreams" || colA === "work stream") {
      destGroupedMappings["Work Streams"].push(rule);
    }
  });

  const generatedIds = new Set();
  const matrixResult = {};

  // Build matrix tables for the 3 tabs
  for (const tabName of ["Objectives", "Key Results", "Work Streams"]) {
    const rules = destGroupedMappings[tabName];
    if (!rules || rules.length === 0) {
      console.log("loadDataMatrix: no mapping rules found for tab '" + tabName + "'.");
      matrixResult[tabName] = { headers: [], rows: [] };
      continue;
    }

    // Sort fields by Column B destination column
    rules.sort((a, b) => a.destColIndex - b.destColIndex);
    const headers = rules.map(r => r.destFieldName || `Col ${r.destColRaw}`);

    // Find first primary mapping rule to calculate source row count
    const primaryRule = rules.find(r => r.originSheetName && !r.isAutogenerated && !r.isDateGenerated && !r.isUiObtained);
    let sourceMatrix = [];

    if (primaryRule && originSheetsCache[primaryRule.originSheetName.toLowerCase()]) {
      sourceMatrix = originSheetsCache[primaryRule.originSheetName.toLowerCase()];
    }

    const totalRows = primaryRule && sourceMatrix.length > 1 ? sourceMatrix.length - 1 : 1;
    console.log("loadDataMatrix: processing tab '" + tabName + "' with " + rules.length + " rules and " + totalRows + " source rows.");
    const tabRows = [];

    for (let r = 1; r <= totalRows; r++) {
      if (r % 100 === 0 || r === totalRows) {
        console.log("loadDataMatrix: tab '" + tabName + "' row " + r + " of " + totalRows + " generated.");
      }

      const rowCells = [];

      rules.forEach(rule => {
        let val = "";

        if (rule.isUiObtained) {
          val = accountId;
        } else if (rule.isDateGenerated) {
          val = new Date();
        } else if (rule.isAutogenerated) {
          val = generateSmartValue(tabName, accountId, generatedIds);
        } else if (rule.originSheetName) {
          const cachedSheet = originSheetsCache[rule.originSheetName.toLowerCase()];
          if (cachedSheet && cachedSheet[r] && cachedSheet[r][rule.originColIndex - 1] !== undefined) {
            val = cachedSheet[r][rule.originColIndex - 1];
          }
        }

        rowCells.push({ value: normalizeMatrixValue(val), destCol: rule.destColIndex });
      });

      tabRows.push(rowCells);
    }

    matrixResult[tabName] = { headers: headers.map(h => normalizeMatrixValue(h)), rows: tabRows };
  }

  const keyResultObjectiveRule = destGroupedMappings["Key Results"].find(rule =>
    rule.originSheetName.trim().toLowerCase() === "krs" && rule.originColIndex === 2
  );
  replaceKeyResultObjectiveDescriptionsWithIds(matrixResult, keyResultObjectiveRule);

  const workstreamKeyResultsMatrix = buildWorkstreamKeyResultsMatrix(originSheetsCache, matrixResult, accountId);
  matrixResult["WorkStreams Key Results"] = workstreamKeyResultsMatrix;

  console.log("loadDataMatrix: returning matrix payload with tabs", Object.keys(matrixResult));
  return normalizeMatrixResult(matrixResult);
}

// =================================================================
// SECTION 3: SMART VALUE GENERATOR
// =================================================================
function generateSmartValue(tabName, accountId, existingSet) {
  const safeAccountId = String(accountId || '').trim();

  let prefix = 'obj';
  if (tabName === 'Key Results') prefix = 'krs';
  if (tabName === 'Work Streams') prefix = 'ws';

  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let formattedId = '';

  do {
    let suffix = '';
    for (let i = 0; i < 6; i++) {
      suffix += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    formattedId = `${safeAccountId}-${prefix}-${suffix}`;
  } while (existingSet.has(formattedId));

  existingSet.add(formattedId);
  return formattedId;
}

function buildWorkstreamKeyResultsMatrix(originSheetsCache, matrixResult, accountId) {
  const workstreamRows = matrixResult["Work Streams"] && matrixResult["Work Streams"].rows ? matrixResult["Work Streams"].rows : [];
  const keyResultRows = matrixResult["Key Results"] && matrixResult["Key Results"].rows ? matrixResult["Key Results"].rows : [];
  const roadmapRows = originSheetsCache["roadmap-workstreams"] || [];
  const sourceKeyResultRows = originSheetsCache["krs"] || [];
  const keyResultLookup = {};

  for (let sourceRowIndex = 1; sourceRowIndex < sourceKeyResultRows.length; sourceRowIndex++) {
    const sourceValue = sourceKeyResultRows[sourceRowIndex][4];
    const matrixRow = keyResultRows[sourceRowIndex - 1];
    const generatedId = findGeneratedId(matrixRow, "krs");
    if (sourceValue !== undefined && String(sourceValue).trim() && generatedId) {
      keyResultLookup[normalizeKeyLookupValue(sourceValue)] = generatedId;
    }
  }

  const relationRows = [];
  const seenRelations = new Set();
  const generatedRelationIds = new Set();
  let totalMatchedPairs = 0;
  const unmatchedKeyResultSamples = new Set();
  const keyResultSourceIndexes = [8, 9];
  console.log("Relation builder: Roadmap rows = " + Math.max(roadmapRows.length - 1, 0) +
    ", KRs rows = " + Math.max(sourceKeyResultRows.length - 1, 0) +
    ", generated Work Stream rows = " + workstreamRows.length +
    ", generated Key Result rows = " + keyResultRows.length +
    ", KRs column E lookup size = " + Object.keys(keyResultLookup).length);

  for (let sourceRowIndex = 1; sourceRowIndex < roadmapRows.length; sourceRowIndex++) {
    const sourceRow = roadmapRows[sourceRowIndex] || [];
    const workstreamId = findGeneratedId(workstreamRows[sourceRowIndex - 1], "ws");
    if (!workstreamId) continue;

    keyResultSourceIndexes.forEach(columnIndex => {
      splitMultiValue(sourceRow[columnIndex]).forEach(value => {
        const keyResultId = keyResultLookup[normalizeKeyLookupValue(value)];
        if (!keyResultId) {
          if (unmatchedKeyResultSamples.size < 5) unmatchedKeyResultSamples.add(value);
          return;
        }

        const relationKey = `${workstreamId}|${keyResultId}`;
        if (seenRelations.has(relationKey)) return;

        seenRelations.add(relationKey);
        totalMatchedPairs += 1;
        const relationId = generateRelationId(accountId, generatedRelationIds);
        relationRows.push([
          relationId,
          workstreamId,
          keyResultId,
          Utilities.formatDate(new Date(), Session.getScriptTimeZone(), "yyyy-MM-dd'T'HH:mm:ss'Z'")
        ].map((value, index) => ({ value: value, destCol: index + 1 })));
      });
    });
  }

  console.log("Relation builder: total matched pairs = " + totalMatchedPairs + ", final relation rows = " + relationRows.length +
    ", unmatched Key Result examples = " + Array.from(unmatchedKeyResultSamples).join(" | "));

  return {
    headers: ["Id", "WorkStream", "Key Results", "Created"],
    rows: relationRows
  };
}

function findGeneratedId(row, prefix) {
  if (!row) return "";
  const idPattern = new RegExp("-" + prefix + "-[A-Z0-9]{6}$", "i");
  const idCell = row.find(cell => cell && idPattern.test(String(cell.value || "").trim()));
  return idCell ? String(idCell.value).trim() : "";
}

function replaceKeyResultObjectiveDescriptionsWithIds(matrixResult, keyResultObjectiveRule) {
  const objectives = matrixResult["Objectives"];
  const keyResults = matrixResult["Key Results"];
  if (!objectives || !objectives.headers || !objectives.rows || !keyResults || !keyResults.rows || !keyResultObjectiveRule) {
    console.log("Objective ID mapping: required matrix data or KRs column B mapper rule is missing.");
    return;
  }

  const shortDescriptionColumnIndex = objectives.headers.findIndex(header => {
    const normalizedHeader = normalizeKeyLookupValue(header);
    return normalizedHeader === "short description" || normalizedHeader === "objective - short";
  });
  const objectiveIdColumnIndex = findIdHeaderIndex(objectives.headers);
  if (shortDescriptionColumnIndex < 0 || objectiveIdColumnIndex < 0) {
    console.log("Objective ID mapping: Objectives matrix requires 'Short Description' and 'Id' columns. Headers = " +
      JSON.stringify(objectives.headers));
    return;
  }

  const objectiveIdsByDescription = new Map();
  objectives.rows.forEach(row => {
    const descriptionCell = row[shortDescriptionColumnIndex];
    const idCell = row[objectiveIdColumnIndex];
    const description = descriptionCell ? String(descriptionCell.value || "").trim() : "";
    const objectiveId = idCell && idCell.value ? String(idCell.value).trim() : "";
    if (description && objectiveId) {
      objectiveIdsByDescription.set(normalizeKeyLookupValue(description), objectiveId);
    }
  });

  console.log("Objective ID mapping: lookup built from Objectives matrix Short Description column " +
    (shortDescriptionColumnIndex + 1) + " and Id column " + (objectiveIdColumnIndex + 1) +
    "; Key Results values sourced from '" + keyResultObjectiveRule.originFieldName +
    "' (KRs column B), destination column " + keyResultObjectiveRule.destColIndex +
    "; lookup entries = " + objectiveIdsByDescription.size);

  let replacedCount = 0;
  const unmatchedDescriptions = new Set();
  keyResults.rows.forEach(row => {
    const objectiveCell = row.find(cell => Number(cell.destCol) === keyResultObjectiveRule.destColIndex);
    const description = objectiveCell ? String(objectiveCell.value || "").trim() : "";
    if (!description) return;

    const objectiveId = objectiveIdsByDescription.get(normalizeKeyLookupValue(description));
    if (objectiveId) {
      objectiveCell.value = objectiveId;
      replacedCount += 1;
    } else if (unmatchedDescriptions.size < 5) {
      unmatchedDescriptions.add(description);
    }
  });

  console.log("Objective ID mapping: replaced " + replacedCount + " Key Results references; unmatched examples = " +
    Array.from(unmatchedDescriptions).join(" | "));
}

function generateRelationId(accountId, generatedRelationIds) {
  const safeAccountId = String(accountId || '').trim();
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let suffix = '';
  let candidate = '';

  do {
    suffix = '';
    for (let i = 0; i < 6; i++) {
      suffix += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    candidate = `${safeAccountId}-wskr-${suffix}`;
  } while (generatedRelationIds.has(candidate));

  generatedRelationIds.add(candidate);
  return candidate;
}

function findHeaderIndex(headers, patterns) {
  for (let i = 0; i < headers.length; i++) {
    const headerValue = normalizeKeyLookupValue(String(headers[i] || ''));
    if (!headerValue) continue;
    if (patterns.some(pattern => headerValue.includes(pattern))) {
      return i;
    }
  }
  return -1;
}

function findNameHeaderIndex(headers, entityPatterns) {
  const normalizedHeaders = headers.map(header => normalizeKeyLookupValue(String(header || '')));
  const exactNameIndex = normalizedHeaders.findIndex(header => header === "name" || header.endsWith(" name"));
  if (exactNameIndex >= 0) return exactNameIndex;

  return normalizedHeaders.findIndex(header =>
    !/(^| )id($| )/.test(header) && entityPatterns.some(pattern => header.includes(pattern))
  );
}

function findIdHeaderIndex(headers) {
  const normalizedHeaders = headers.map(header => normalizeKeyLookupValue(String(header || '')));
  const exactIndex = normalizedHeaders.findIndex(header => header === "id");
  if (exactIndex >= 0) return exactIndex;

  return normalizedHeaders.findIndex(header => /(^| )id$/.test(header));
}

function findHeaderIndexFromRow(row, patterns) {
  for (let i = 0; i < row.length; i++) {
    const cellValue = normalizeKeyLookupValue(String(row[i] || ''));
    if (!cellValue) continue;
    if (patterns.some(pattern => cellValue.includes(pattern))) {
      return i;
    }
  }
  return -1;
}

function normalizeKeyLookupValue(value) {
  return String(value || '').trim().toLowerCase().replace(/\s+/g, ' ');
}

function prepareOriginSheetRows(rawRows, sheetName) {
  const rowsToSkip = String(sheetName || '').trim().toLowerCase() === "objectives" ? 2 : 0;
  return rawRows.slice(rowsToSkip).filter((row, index) => {
    if (index === 0) return true;
    const cellBValue = row && row[1] !== undefined ? row[1] : "";
    return String(cellBValue).trim() !== "";
  });
}

function splitMultiValue(value) {
  if (value === undefined || value === null || value === '') return [];
  const text = String(value).trim();
  if (!text) return [];
  return text
    .split(/[\n,;|]+/)
    .map(item => item.trim())
    .filter(item => item !== '');
}

function getSourceColumnIndexes(headerRow) {
  return [9, 10].filter(columnIndex => columnIndex <= headerRow.length);
}

// =================================================================
// SECTION 4: IMPORT MATRIX & WRITE LOGS (STAGE 2)
// =================================================================
function importMatrixToDestination(payload) {
  const { matrixData, runNumber } = payload;
  const systemSettings = getSystemSettings();
  const destUrl = systemSettings.destinationUrl;
  const mapperUrl = systemSettings.mapperUrl;

  if (!destUrl || !mapperUrl || !matrixData) {
    throw new Error("v" + APP_VERSION + " Error: System destination URL, mapper URL, and matrix data are required.");
  }

  const destSpreadsheet = SpreadsheetApp.openByUrl(destUrl);
  const mapperSpreadsheet = SpreadsheetApp.openByUrl(mapperUrl);

  const executionLog = [];
  const timestamp = new Date().toISOString();
  const destinationTabNames = {
    "Work Streams": "Workstreams",
    "WorkStreams Key Results": "Workstream Key Results"
  };

  try {
    for (const tabCategory in matrixData) {
      const tabObj = matrixData[tabCategory];
      if (!tabObj || !tabObj.rows || tabObj.rows.length === 0) continue;

      const destinationTabName = destinationTabNames[tabCategory] || tabCategory;
      let destSheet = destSpreadsheet.getSheetByName(destinationTabName);
      if (!destSheet) {
        destSheet = destSpreadsheet.insertSheet(destinationTabName);
      }

      const rowsToWrite = tabObj.rows.map(row => row.map(cell => cell.value));
      const startRow = destSheet.getLastRow() === 0 ? 1 : destSheet.getLastRow() + 1;

      destSheet.getRange(startRow, 1, rowsToWrite.length, rowsToWrite[0].length).setValues(rowsToWrite);

      executionLog.push([
        timestamp,
        runNumber,
        "SUCCESS",
        `Appended ${rowsToWrite.length} rows to destination tab '${destinationTabName}'.`
      ]);
    }
  } catch (err) {
    executionLog.push([
      timestamp,
      runNumber,
      "ERROR",
      `Execution failed: ${err.message}`
    ]);
    writeLogsToMapper(mapperSpreadsheet, executionLog);
    throw err;
  }

  writeLogsToMapper(mapperSpreadsheet, executionLog);
  return { success: true, message: "Data successfully imported into Casper!" };
}

// =================================================================
// SECTION 5: HELPER UTILITIES
// =================================================================
function writeLogsToMapper(mapperSpreadsheet, logEntries) {
  let logSheet = mapperSpreadsheet.getSheetByName("Logs");
  if (!logSheet) {
    logSheet = mapperSpreadsheet.insertSheet("Logs");
    logSheet.appendRow(["Timestamp", "Run Number", "Status", "Details"]);
    logSheet.getRange("A1:D1").setFontWeight("bold").setBackground("#F4F6F8");
  }

  if (logEntries.length > 0) {
    const lastRow = logSheet.getLastRow() + 1;
    logSheet.getRange(lastRow, 1, logEntries.length, 4).setValues(logEntries);
  }
}

function parseColumnIndex(col) {
  if (typeof col === 'number') return col;
  if (!col) return 1;
  col = col.toString().toUpperCase().trim();
  
  // Handle numeric string conversion
  if (!isNaN(col)) return parseInt(col, 10);

  // Convert A, B, C ... Z, AA, AB to 1-based index
  let base = 0;
  for (let i = 0; i < col.length; i++) {
    base = base * 26 + col.charCodeAt(i) - 64;
  }
  return base > 0 ? base : 1;
}

function normalizeMatrixValue(value) {
  if (value === undefined || value === null) return "";
  if (value instanceof Date) {
    return Utilities.formatDate(value, Session.getScriptTimeZone(), "yyyy-MM-dd'T'HH:mm:ss'Z'");
  }
  return String(value);
}

function normalizeMatrixResult(matrixResult) {
  const safeResult = {};
  Object.keys(matrixResult).forEach(tabName => {
    const tab = matrixResult[tabName] || { headers: [], rows: [] };
    safeResult[tabName] = {
      headers: (tab.headers || []).map(header => normalizeMatrixValue(header)),
      rows: (tab.rows || []).map(row => (row || []).map(cell => ({
        value: normalizeMatrixValue(cell && cell.value),
        destCol: cell && cell.destCol !== undefined ? cell.destCol : 0
      })))
    };
  });
  return safeResult;
}