/**
 * Casper CSP Migration Tool - Backend Engine
 * VERSION: 2.0.0
 */

const SYSTEM_SETTINGS = {
  mapperUrl: "https://docs.google.com/spreadsheets/d/1wVd0ETR-kRlnFcBrwLBw229qJ1gYZ3y3leGbnj3cn24/edit?gid=0#gid=0",
  destinationUrl: "https://docs.google.com/spreadsheets/d/1wycfLNwduWrGLjfzjng701beyVk3YIzVCdl38rMc_v0/edit?gid=363370443#gid=363370443"
};

// =================================================================
// SECTION 1: WEB APP ENTRY POINT
// =================================================================
function doGet() {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('Casper CSP Migration Tool v2.0.0')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// =================================================================
// SECTION 2: DATA MATRIX GENERATION (STAGE 1)
// =================================================================
function loadDataMatrix(payload) {
  const { originUrl, accountId } = payload;

  if (!originUrl || !accountId) {
    throw new Error("v2.0.0 Error: Origin URL and Account ID are required.");
  }

  if (!SYSTEM_SETTINGS.mapperUrl || SYSTEM_SETTINGS.mapperUrl === "PASTE_MAPPER_SPREADSHEET_URL_HERE") {
    throw new Error("v2.0.0 Error: Mapper URL is not configured in system settings.");
  }

  const originSpreadsheet = SpreadsheetApp.openByUrl(originUrl);
  const mapperSpreadsheet = SpreadsheetApp.openByUrl(SYSTEM_SETTINGS.mapperUrl);
  const mapperSheet = mapperSpreadsheet.getSheetByName("Mapper") || mapperSpreadsheet.getActiveSheet();

  if (!mapperSheet) {
    throw new Error("v2.0.0 Error: 'Mapper' sheet tab was not found.");
  }

  // Pre-cache origin sheets in memory
  const originSheetsCache = {};
  originSpreadsheet.getSheets().forEach(sheet => {
    originSheetsCache[sheet.getName().trim().toLowerCase()] = sheet.getDataRange().getValues();
  });

  const mapperData = mapperSheet.getDataRange().getValues();
  mapperData.shift(); // Remove header row

  // Target 3 tabs strictly
  const destGroupedMappings = {
    "Objectives": [],
    "Key Results": [],
    "Work Streams": []
  };

  // Group rules by Column A value
  mapperData.forEach(row => {
    const colA = String(row[0] || '').trim().toLowerCase();
    if (!colA) return;

    const colGValue = String(row[6] || '').trim().toLowerCase();

    const rule = {
      destCategory: String(row[0] || '').trim(),
      destColIndex: parseColumnIndex(row[1]),          // Column B
      destColRaw: String(row[1] || '').trim(),        // Column B raw
      destFieldName: String(row[2] || '').trim(),     // Column C
      originSheetName: String(row[3] || '').trim(),   // Column D
      originColIndex: parseColumnIndex(row[4]),        // Column E
      originFieldName: String(row[5] || '').trim(),   // Column F
      isAutogenerated: colGValue === 'yes',             // Column G
      isDateGenerated: colGValue === 'date',           // Column G
      isUiObtained: String(row[7] || '').trim().toLowerCase() === 'yes'      // Column H
    };

    if (colA === "objectives" || colA === "objective") {
      destGroupedMappings["Objectives"].push(rule);
    } else if (colA === "key results" || colA === "key result" || colA === "kr") {
      destGroupedMappings["Key Results"].push(rule);
    } else if (colA === "work streams" || colA === "workstreams" || colA === "work stream") {
      destGroupedMappings["Work Streams"].push(rule);
    }
  });

  const generatedIds = new Set();
  const matrixResult = {};

  // Build matrix tables for the 3 tabs
  for (const tabName of ["Objectives", "Key Results", "Work Streams"]) {
    const rules = destGroupedMappings[tabName];
    if (!rules || rules.length === 0) {
      matrixResult[tabName] = { headers: [], rows: [] };
      continue;
    }

    // Sort fields by Column B destination column
    rules.sort((a, b) => a.destColIndex - b.destColIndex);
    const headers = rules.map(r => r.destFieldName || `Col ${r.destColRaw}`);

    // Find first primary mapping rule to calculate source row count
    const primaryRule = rules.find(r => r.originSheetName && !r.isAutogenerated && !r.isDateGenerated && !r.isUiObtained);
    let sourceMatrix = [];

    if (primaryRule && originSheetsCache[primaryRule.originSheetName.toLowerCase()]) {
      sourceMatrix = originSheetsCache[primaryRule.originSheetName.toLowerCase()];
    }

    const totalRows = primaryRule && sourceMatrix.length > 1 ? sourceMatrix.length - 1 : 1;
    const tabRows = [];

    for (let r = 1; r <= totalRows; r++) {
      const rowCells = [];

      rules.forEach(rule => {
        let val = "";

        if (rule.isUiObtained) {
          val = accountId;
        } else if (rule.isDateGenerated) {
          val = new Date();
        } else if (rule.isAutogenerated) {
          val = generateSmartValue(rule.destFieldName, accountId, rule.originSheetName, generatedIds);
        } else if (rule.originSheetName) {
          const cachedSheet = originSheetsCache[rule.originSheetName.toLowerCase()];
          if (cachedSheet && cachedSheet[r] && cachedSheet[r][rule.originColIndex - 1] !== undefined) {
            val = cachedSheet[r][rule.originColIndex - 1];
          }
        }

        rowCells.push({ value: val, destCol: rule.destColIndex });
      });

      tabRows.push(rowCells);
    }

    matrixResult[tabName] = { headers: headers, rows: tabRows };
  }

  return matrixResult;
}

// =================================================================
// SECTION 3: SMART VALUE GENERATOR
// =================================================================
function generateSmartValue(fieldName, accountId, sheetName, existingSet) {
  const safeAccountId = String(accountId || '').trim();
  const safeSheetName = String(sheetName || 'Sheet')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^A-Za-z0-9_-]/g, '');

  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let formattedId = '';

  do {
    let suffix = '';
    for (let i = 0; i < 4; i++) {
      suffix += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    formattedId = `${safeAccountId}-${safeSheetName}-${suffix}`;
  } while (existingSet.has(formattedId));

  existingSet.add(formattedId);
  return formattedId;
}

// =================================================================
// SECTION 4: IMPORT MATRIX & WRITE LOGS (STAGE 2)
// =================================================================
function importMatrixToDestination(payload) {
  const { matrixData, runNumber } = payload;
  const destUrl = SYSTEM_SETTINGS.destinationUrl;
  const mapperUrl = SYSTEM_SETTINGS.mapperUrl;

  if (!destUrl || !mapperUrl || !matrixData) {
    throw new Error("v2.0.0 Error: System destination URL, mapper URL, and matrix data are required.");
  }

  const destSpreadsheet = SpreadsheetApp.openByUrl(destUrl);
  const mapperSpreadsheet = SpreadsheetApp.openByUrl(mapperUrl);

  const executionLog = [];
  const timestamp = new Date().toISOString();

  try {
    for (const tabCategory in matrixData) {
      const tabObj = matrixData[tabCategory];
      if (!tabObj || !tabObj.rows || tabObj.rows.length === 0) continue;

      let destSheet = destSpreadsheet.getSheetByName(tabCategory);
      if (!destSheet) {
        destSheet = destSpreadsheet.insertSheet(tabCategory);
      }

      const rowsToWrite = tabObj.rows.map(row => row.map(cell => cell.value));
      const startRow = destSheet.getLastRow() === 0 ? 1 : destSheet.getLastRow() + 1;

      destSheet.getRange(startRow, 1, rowsToWrite.length, rowsToWrite[0].length).setValues(rowsToWrite);

      executionLog.push([
        timestamp,
        runNumber,
        "SUCCESS",
        `Appended ${rowsToWrite.length} rows to destination tab '${tabCategory}'.`
      ]);
    }
  } catch (err) {
    executionLog.push([
      timestamp,
      runNumber,
      "ERROR",
      `Execution failed: ${err.message}`
    ]);
    writeLogsToMapper(mapperSpreadsheet, executionLog);
    throw err;
  }

  writeLogsToMapper(mapperSpreadsheet, executionLog);
  return { success: true, message: `Run #${runNumber}: Data successfully imported into Destination Sheet!` };
}

// =================================================================
// SECTION 5: HELPER UTILITIES
// =================================================================
function writeLogsToMapper(mapperSpreadsheet, logEntries) {
  let logSheet = mapperSpreadsheet.getSheetByName("Logs");
  if (!logSheet) {
    logSheet = mapperSpreadsheet.insertSheet("Logs");
    logSheet.appendRow(["Timestamp", "Run Number", "Status", "Details"]);
    logSheet.getRange("A1:D1").setFontWeight("bold").setBackground("#F4F6F8");
  }

  if (logEntries.length > 0) {
    const lastRow = logSheet.getLastRow() + 1;
    logSheet.getRange(lastRow, 1, logEntries.length, 4).setValues(logEntries);
  }
}

function parseColumnIndex(col) {
  if (typeof col === 'number') return col;
  if (!col) return 1;
  col = col.toString().toUpperCase().trim();
  
  // Handle numeric string conversion
  if (!isNaN(col)) return parseInt(col, 10);

  // Convert A, B, C ... Z, AA, AB to 1-based index
  let base = 0;
  for (let i = 0; i < col.length; i++) {
    base = base * 26 + col.charCodeAt(i) - 64;
  }
  return base > 0 ? base : 1;
}